services:
  - type: web
    name: evalassist
    runtime: node
    plan: free
    buildCommand: npm install; npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
